### ISSUE TITLE
Icon does not change itself to clear

### ISSUE THREAD

**Issue by XRayAdamo** [dwiyatci/jquery-inputsearch#3]
Hello

I found this plugin very useful, but here is one problem. If input contains value on page load, the icon remains as "search", but it should be "clear". Only when you change something inside input it changes itself to "clear".

**Comment by dwiyatci** [comment]
Hi,

sorry it takes me almost a year to come back to you (and this repo) — my new job has been quite seizing my time. Thanks for your interest of using this plugin. Recently I have revamped the plugin, and I believe I have resolved this issue. Please give it a shot! =)

/gd
